In [17]:
import pandas as pd

In [18]:
df_ppublic = pd.read_csv('../dat/tmp/tsa_ppublic.csv', delimiter='\t').set_index('tsa')

In [19]:
df_ppublic.head()

       ppublic
tsa
tsa01     0.84
tsa02     0.96
tsa03     0.98
tsa04     0.86
tsa05     0.81

In [20]:
df_targets = pd.read_csv('../dat/targets.csv').set_index('tsa')

In [21]:
vcut_sum_target = df_targets['vcut'].sum()

In [22]:
df_targets = df_targets.join(df_ppublic)

In [23]:
df_targets.head()

       period     vcut   abrn  cflw_acut_e  cgen_vcut_e  cgen_abrn_e  ppublic
tsa
tsa01       1  5059910  10092          0.1         0.01         0.01     0.84
tsa01       2  5059910  10092          0.1         0.01         0.01     0.84
tsa01       3  5059910  10092          0.1         0.01         0.01     0.84
tsa01       4  5059910  10092          0.1         0.01         0.01     0.84
tsa02       1  7000000   3950          0.1         0.01         0.01     0.96

In [24]:
for c in ['vcut', 'abrn']:
    df_targets[c] = (df_targets[c] * df_targets['ppublic']).astype(int)

In [25]:
df_targets = df_targets.drop('ppublic', 1)

In [26]:
df_targets.head()

       period     vcut  abrn  cflw_acut_e  cgen_vcut_e  cgen_abrn_e
tsa
tsa01       1  4250324  8477          0.1         0.01         0.01
tsa01       2  4250324  8477          0.1         0.01         0.01
tsa01       3  4250324  8477          0.1         0.01         0.01
tsa01       4  4250324  8477          0.1         0.01         0.01
tsa02       1  6720000  3792          0.1         0.01         0.01

In [27]:
vcutp1_sum_target =  54815521 
vcutp1_sum = df_targets.reset_index().set_index(['tsa', 'period'])['vcut'].loc[:, 1].sum() * 0.1

In [28]:
vcutp1_sum_target, vcutp1_sum

(54815521, 56486538.300000004)

In [29]:
df_targets['vcut'] = (df_targets['vcut'] * vcut_sum_target / df_targets['vcut'].sum()).astype(int)

In [30]:
df_targets.reset_index().set_index(['tsa', 'period'])['vcut'].loc[:, 1].sum() * 0.1

60320143.5

In [31]:
df_targets.head()

       period     vcut  abrn  cflw_acut_e  cgen_vcut_e  cgen_abrn_e
tsa
tsa01       1  4538783  8477          0.1         0.01         0.01
tsa01       2  4538783  8477          0.1         0.01         0.01
tsa01       3  4538783  8477          0.1         0.01         0.01
tsa01       4  4538783  8477          0.1         0.01         0.01
tsa02       1  7176070  3792          0.1         0.01         0.01

In [32]:
df_targets.to_csv('../dat/tmp/targets.csv')